### ISSUE TITLE
error:0308010C: Digital Evnelope Routines::unsupported

### ISSUE THREAD

**Issue by koramint** [cadon0/gif-to-the-beat#41]
Currently having an issue where it crashes after starting up for a second and it gives me this.
(starting with start cmd /k start.bat)

![image](https://user-images.githubusercontent.com/64286915/210184771-b921e9ce-cdc7-4f2c-b87d-44f68bd97e8f.png)

I've gone through different node versions with no avail

**Comment by koramint** [comment]
Got past that after a minute, then I'm getting this

![image](https://user-images.githubusercontent.com/64286915/210184876-707e955a-98ed-4adb-a2d7-5cd32b8a8aea.png)

Then after trying to update it gives me this:

![image](https://user-images.githubusercontent.com/64286915/210184881-9c4a237a-d868-4320-9bcf-307dc8de0bf4.png)
Not really sure what to do anymore

**Comment by koramint** [comment]
it was not because of the @lastest suprisingly

**Comment by koramint** [comment]
fixed it, ended up being the node version just downgraded to some 16.3.2 or something and most of the issues were fixed. google really is your best friend

**Comment by cadon0** [comment]
Thanks!

I did see an issue with Node 18 where it would be unable to connect and only show this (now fixed):
![image](https://user-images.githubusercontent.com/25311843/210188287-b1ae3f59-290e-4a26-8174-65f3c09a595f.png)

Not sure about "digital envelope routines" since I don't get that error, could be security settings? 🤷 

And don't worry about the `browserslist --update-db` thing, that should be fine even if out of date 🙂 it just tries to make sure that the animation loads correctly in different web browsers

**Comment by koramint** [comment]
Yup everything worked after I did that and tbh you might be right I think I just ran it as admin to fix that one. Thanks for the tip <3
